Models/Aluno.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace MVCAlunos.Models
{
    public enum EnumeradorSexo
    {
        Masculino = 0,
        Feminino = 1
    }
    public class Aluno
    {
        [Key]

        [Display(Name = "Id")]
        public int Matricula { get; set; }

        [StringLength(60, MinimumLength = 3)]
        [Required]
        public string Nome { get; set; }

        [StringLength(11, MinimumLength = 11, ErrorMessage = "O Campo CPF deve ter 11 dígitos. ")]
        public string Cpf { get; set; }


        [DataType(DataType.Date)]
        public DateTime Nascimento { get; set; }

        public EnumeradorSexo? Sexo { get; set; }
    }
}

Controllers/AlunosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using FirebirdSql.Data.FirebirdClient;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCAlunos.Data;
using MVCAlunos.Data.Banco;
using MVCAlunos.Data.DAL;
using MVCAlunos.Models;
using MVCAlunos.ViewModel;

namespace MVCAlunos.Controllers
{
    public class AlunosController : Controller
    {
        /*private readonly MVCAlunosContext _context;
        private readonly IHttpClientFactory _httpClientFactory;*/

        // public AlunosController(//MVCAlunosContext context, IHttpClientFactory httpClientFactory//
        // )
        //{
        /* _context = context;
         _httpClientFactory = httpClientFactory;
*/
        //}

        // GET: Alunos

        /* public async Task<IActionResult> Index(string searchString)
         {
             var alunos = from a in _context.Aluno
                          select a;

             if (!String.IsNullOrEmpty(searchString))
             {
                 alunos = alunos.Where(s => s.Nome!.Contains(searchString));
             }

             return View(await alunos.ToListAsync());
         }*/
        public IActionResult Index()
        {
            DAL CONNECTAR = new();
            var dt = CONNECTAR.RetDataTable("select * from TBALUNO");
            List<LAlunosViewModel> Listar_alunos = LAlunosViewModel.ListarTabela(dt);
            ViewBag.Alunos = Listar_alunos;
            return View();
        }
        public IActionResult ListagemAlunos()
        {
            Banco conexao = new();

            List<LAlunosViewModel> listaAlunos = new List<LAlunosViewModel>();

            if (conexao.bconexao)
            {
                var dt = conexao.RetornoTabela("select * from TBALUNO");
                LAlunosViewModel tratarAlunos = new();
                listaAlunos = LAlunosViewModel.ListarTabela(dt);
                //listaAlunos = tratarAlunos.ListarTabela(dt);

            }
            ViewBag.Alunos = listaAlunos;
            return View();
        }

        [HttpPost]
        public string Index(string searchString, bool notUsed)
        {
            return "From [HttpPost]Index: filter on " + searchString;
        }

        // GET: Alunos/Details/5
        /*public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Aluno == null)
            {
                return NotFound();
            }

            var aluno = await _context.Aluno
                .FirstOrDefaultAsync(m => m.Matricula == id);
            if (aluno == null)
            {
                return NotFound();
            }

            return View(aluno);
        }*/

        // GET: Alunos/Create
        public IActionResult Create()
        {


            return View();
        }

        // POST: Alunos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        /*  [HttpPost]
          [ValidateAntiForgeryToken]
          public async Task<IActionResult> Create([Bind("Matricula,Nome,Cpf,Nascimento,Sexo")] Aluno aluno)
          {
              if (ModelState.IsValid)
              {
                  _context.Add(aluno);
                  await _context.SaveChangesAsync();
                  return RedirectToAction(nameof(Index));
              }
              return View(aluno);
          }
  */
        // GET: Alunos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            DAL CONNECTAR = new();
            var dt = CONNECTAR.RetDataTable($"SELECT * FROM TBALUNO WHERE TBALUNO.MATRICULA = {id}");
            List<LAlunosViewModel> Listar_alunos = LAlunosViewModel.ListarTabela(dt);

            ViewBag.Alunos = Listar_alunos;
            return View();
        }



        // GET: Alunos/AddorEdit/
        /* public IActionResult AddOrEdit(int? id)
         {
             Aluno aluno = new();
             return View(aluno);
         }*/


        // POST: Alunos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        /* public async Task<IActionResult> Edit(int id, [Bind("Matricula,Nome,Cpf,Nascimento,Sexo")] Aluno aluno)
         {
             if (id != aluno.Matricula)
             {
                 return NotFound();
             }

             if (ModelState.IsValid)
             {
                 try
                 {
                     _context.Update(aluno);
                     await _context.SaveChangesAsync();
                 }
                 catch (DbUpdateConcurrencyException)
                 {
                     if (!AlunoExists(aluno.Matricula))
                     {
                         return NotFound();
                     }
                     else
                     {
                         throw;
                     }
                 }
                 return RedirectToAction(nameof(Index));
             }
             return View(aluno);
         }*/

        public IActionResult AddOrEdit(int id, [Bind("Matricula,Nome,Cpf,Nascimento,Sexo")] Aluno aluno)
        {

            if (ModelState.IsValid)
            {

            }
            return View();
        }

        // GET: Alunos/Delete/5
        /* public async Task<IActionResult> Delete(int? id)
         {
             if (id == null || _context.Aluno == null)
             {
                 return NotFound();
             }

             var aluno = await _context.Aluno
                 .FirstOrDefaultAsync(m => m.Matricula == id);
             if (aluno == null)
             {
                 return NotFound();
             }

             return View(aluno);
         }*/
       /* public IActionResult Delete(int? id)
        {
            DAL CONNECTAR = new();
            var dt = CONNECTAR.RetDataTable("SELECT * FROM TBALUNO");
            List<LAlunosViewModel> Listar_alunos = LAlunosViewModel.ListarTabela(dt);
            ViewBag.Alunos = Listar_alunos;
            return View();
        }*/

        // POST: Alunos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        /* public async Task<IActionResult> DeleteConfirmed(int id)
         {
             if (_context.Aluno == null)
             {
                 return Problem("Entity set 'MVCAlunosContext.Aluno'  is null.");
             }
             var aluno = await _context.Aluno.FindAsync(id);
             if (aluno != null)
             {
                 _context.Aluno.Remove(aluno);
             }

             await _context.SaveChangesAsync();
             return RedirectToAction(nameof(Index));
         }*/

        public IActionResult DeleteConfirmed(int id)
        {
            return RedirectToAction(nameof(Index));
        }

        /* private bool AlunoExists(int id)
         {
           return _context.Aluno.Any(e => e.Matricula == id);
         }*/

        public void Delete(object sender, EventArgs e)
        {
            string sql_Delete = "delete from TBALUNO WHERE MATRICULA = @MATRICULA"; //tenta fazer o insert no banco try { //abre a conexão com o banco de dados this.conexao_FB.abre_Conexao(); //cria uma nova instancia para FbDataAdapter passando como //parâmetro a string com o comando SQL e a conexão com o banco de dados this.adapt = new FbDataAdapter(sql_Delete, this.conexao_FB.get_Conexao()); //limpa os parâmetros caso exista algum this.adapt.SelectCommand.Parameters.Clear(); // informa para o FbDataAdapter quais são os conteudos de cada parâmetro this.adapt.SelectCommand.Parameters.Add("@nome", tx_nome_cliente.Text); // executa o FbDataAdapter com o comando ExecuteNonQuery e retorna o total de linhas afetadas int numero = this.adapt.SelectCommand.ExecuteNonQuery(); //mensagem MessageBox.Show("Clientes Excluídos: " + numero.ToString(), "Atenção", MessageBoxButtons.OK, MessageBoxIcon.Information); } // caso de algum erro catch (Exception er) { // mensagem de erro MessageBox.Show("Erro ao fazer exclusão: " + er.Message, "Atenção", MessageBoxButtons.OK, MessageBoxIcon.Error); } //fecha a conexao com o banco de dados finally { this.conexao_FB.fecha_Conexao(); } }

            try
            {
                DAL CONNECTAR = new();
                CONNECTAR.DelDataTable(sql_Delete);

            }
            catch (Exception er)
            {

                throw er;

            }
            
        }
    }
}

Views/Alunos/Create.cshtml
@model MVCAlunos.Models.Aluno

@{
    ViewData["Title"] = "Create";
}

<h1>Criar</h1>

<h4>Aluno</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cpf" class="control-label"></label>
                <input asp-for="Cpf" class="form-control" />
                <span asp-validation-for="Cpf" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nascimento" class="control-label"></label>
                <input asp-for="Nascimento" class="form-control" />
                <span asp-validation-for="Nascimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sexo" class="control-label"></label>
                <input asp-for="Sexo" class="form-control" />
                <span asp-validation-for="Sexo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">
        <button type="button" class="btn btn-dark">
            Voltar
        </button>
    </a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Views/Alunos/Delete.cshtml
@model MVCAlunos.Models.Aluno

@{
    ViewData["Title"] = "Delete";
}

<h1>Deletar</h1>

<h3 style="color: red;">Tem Certeza que quer deletar esse aluno?</h3>
<div>
    <h4>Aluno</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.Alunos

        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cpf)

        </dt>
        <dd class="col-sm-10">
            @ViewBag.Alunos

        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nascimento)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.Alunos

        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>
        <dd class="col-sm-10">
            @ViewBag.Alunos

        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Matricula" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index">
            <button type="button" class="btn btn-dark">
                Voltar
            </button>
        </a>
    </form>
</div>

Views/Alunos/Details.cshtml
@model MVCAlunos.Models.Aluno

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes</h1>

<div>
    <h4>Aluno</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cpf)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cpf)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nascimento)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nascimento)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Sexo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Matricula" style="color: inherit; text-decoration: none;">
        <button type="button" class="btn btn-outline-primary">
            <i class="bi bi-pencil-fill"></i>
        </button>
    </a>
    <a asp-action="Index">
        <button type="button" class="btn btn-dark">
            Voltar
        </button>
    </a>
</div>

Views/Alunos/Edit.cshtml
@model MVCAlunos.Models.Aluno

@{
    ViewData["Title"] = "Editar Aluno";
}

<h1>@ViewData["Title"]</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Matricula" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cpf" class="control-label"></label>
                <input asp-for="Cpf" class="form-control" />
                <span asp-validation-for="Cpf" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nascimento" class="control-label"></label>
                <input asp-for="Nascimento" class="form-control" />
                <span asp-validation-for="Nascimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sexo" class="control-label"></label>
                <input asp-for="Sexo" class="form-control" />
                <span asp-validation-for="Sexo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-dark" style="width=22em; height=20px;"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">
        <button type="button" class="btn btn-dark">
            Voltar
        </button>
    </a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Views/Alunos/Index.cshtml
@model IEnumerable<MVCAlunos.Models.Aluno>

@{
    ViewData["Title"] = "Tabela de Alunos";
}

<h1>Tabela de Alunos</h1>

<p>
    <a asp-action="Create" style="color: inherit; text-decoration: none;">
        <button type="button" class="btn btn-dark">
            Adicionar Aluno
        </button>
    </a>
    <form asp-controller="Alunos" asp-action="Index" method="get">
        <div>
            <input type="radio" id="nome" name="option" value="nome" checked>
            <label for="nome">Nome</label>
            <input type="radio" id="matricula" name="option" value="matricula">
            <label for="matricula">Matrícula</label>
        </div>
        <div class="input-group mb-3" style="width: 20em;">
            <input type="text" name="SearchString" placeholder="Insira nome/matricula"  class="form-control"/>
            <input type="submit" value="Filter" class="btn btn-outline-secondary"/>
        </div>
    </form>

</p>
<table class="table table-striped">
    <thead class="table-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Matricula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sexo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nascimento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cpf)
            </th>
            <th>Opções</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in ViewBag.Alunos)
        {
            <tr>
                <td>
                    @*@Html.DisplayFor(modelItem => item.Matricula)*@
                    @item.MATRICULA
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.Nome)*@
                    @item.NOME
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.Sexo)*@
                    @item.SEXO
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.Nascimento)*@
                    @item.NASCIMENTO.ToString("dd/MM/yyyy")
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.Cpf)*@
                    @item.CPF
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.MATRICULA" style="color: inherit; text-decoration: none;">
                        <button type="button" class="btn btn-outline-primary">
                            <i class="bi bi-pencil-fill"></i>
                        </button>
                    </a>
                    <a asp-action="Details" asp-route-id="@item.MATRICULA" style="color: inherit; text-decoration: none;">
                        <button type="button" class="btn btn-outline-primary">
                            <i class="bi bi-list"></i>
                        </button>
                    </a>
                    <a asp-action="Delete" asp-route-id="@item.MATRICULA" style="color: inherit; text-decoration: none;">
                        <button type="button" class="btn btn-outline-danger">
                            <i class="bi bi-trash-fill"></i>
                        </button>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>